<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>ArcticJoiner</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="ArcticJoiner.cs" LogicalName="ArcticJoiner.cs" />
  </ItemGroup>
</Project>
